### ISSUE TITLE
求大佬教一下怎么反编译QVMProtect这种加密的代码

### ISSUE THREAD

**Issue by chenshiforever** [yunowo/BJUTWiFi#92]
哈哈，这个是智慧树知到app最新版用的壳，用dumpdex不能反编译出来这一段加密的代码，在你这个项目下提这个问题主要是看你好像没怎么更新其他项目了，只有这个项目可能会有一丝丝机会回复我吧~，谢谢你
QVMProtect是360加固里面的VMP加固，这个太难了啊
dump出来的代码是下面这种形式

    @QVMProtect
    public final native String dbp(String str, String str2);

    @QVMProtect
    private final native String ebp(String str, String str2);

    @QVMProtect
    private final native String getEk(Emodule emodule);

**Comment by yunowo** [comment]
没有简单方法.
